# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://localhost:3306/ry?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: xiaoxiao
      # 从库数据源
      slave:
        # 从数据库开关/默认关闭
        enabled: true
        url: jdbc:sqlserver://61.152.122.117:1433;databasename=ScreenData80JD
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        username: ENC(ADDA5YGPCQkG4GA6++pebA==)
        password: ENC(c+kkwn72SPEBurPQd90+ytsR+KLWcdDv)
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效    SELECT 1 FROM DUAL
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /monitor/druid/*
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          #merge sql error, dbType sqlserver, druid, sql: null
          #将merge-sql: true 改为  merge-sql: false.
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  wechat:
    # 公众测试平台
    appID: wxf3d8985e96e0af37
    appsecret: 2690e82fe3c07f63d2ae1baf0c085b89
    base_url:
    wechat_token: louyi_wechat!1357$